module CD_thermo
   use global
   implicit none  

   public :: CD_thermo_run

   contains
   
   !==============================================================================
   ! CD_thermo_run
   !==============================================================================
   ! This module calculates the thermodynamical quantities along the shock (number)
   ! coincident with the CD trayectory (curve generated by CD.f90).
   ! Output: termo(number).dat. It also calculates the inject luminosity at 
   ! each shock segment.
   !==============================================================================
   
   subroutine CD_thermo_run(number,D)
      character, intent(in) :: number
      real(dp), intent(in) :: D
      real(dp) :: R(ml), Dy(ml), Dx(ml), Dl(ml)
      real(dp) :: L_wind, Mdot, vinf, mu_s, mu_es, mu_is, v_rot, Rst, Lst, r_A_st, frac_B
      real(dp) :: normal(3), perp(ml)
      real(dp) :: Beq0, rhow(ml), L_inj(ml), L_inj_tot
      real(dp) :: dydx(ml), nor, Xst(3) 
      real(dp) :: e_flux, dA_perp
      !real(dp) :: dtheta(ml),dtheta_prom,dOmega
      real(dp) :: cte_T, cte_ad, Cs(ml)
      real(dp) :: y_min, dot_M, dM
      real(dp) :: chi_rad, chi_ic
      integer :: l2, l_crit, l_min

      call validate_shock_number(number,'CD_thermo_run')

      if (verbose) print *, '\n Calculate thermodynamic variables in S',number

      if (number=='1') then 
         Mdot = Mdot1
         vinf = vinf1
         Rst = Rst1
         Lst = Lst1
         mu_s = mu_1 
         mu_is = mu_i1 
         mu_es = mu_e1 
         v_rot = v_rot1
         frac_B = frac_B1
         r_A_st = r_A_st1
         Xst = (/ 0.d0, 0.d0, 0.d0 /)
       else
         Mdot = Mdot2
         vinf = vinf2
         Rst = Rst2
         Lst = Lst2
         mu_s = mu_2 
         mu_is = mu_i2 
         mu_es = mu_e2 
         v_rot = v_rot2
         frac_B = frac_B2
         r_A_st = r_A_st2
         Xst = (/ D, 0.d0, 0.d0 /)
       end if


      !-----------------------------------------------------------------
      ! Calculate some geometrical quantities

      do l = 1, ml_2
         if (number=='1') then        
            R(l) = sqrt(x(l)**2+y(l)**2)     ! Distance from the point to the star 1
         else
            R(l) = sqrt((D-x(l))**2+y(l)**2) ! Distance from the point to the star 2
         end if

         if (l == 1) then
            Dx(1) = 0.d0     ! it starts moving vertically 
            Dy(1) = y(1)
         else
            Dx(l) = x(l)-x(l-1)
            Dy(l) = y(l)-y(l-1)
         end if
         Dl(l) = sqrt( Dx(l)**2 + Dy(l)**2 )
         !dtheta(l) = atan(Dl(l)/R(l))
      end do

      open(43,file=output_file('n_perp'//number//'.dat'))
      open(44,file=output_file('n_tan.dat'))
      do l = 1, ml_2
         read(44,*) l2, dydx(l)
         nor = 1./sqrt( 1. + dydx(l)**2 )
         normal = (/ -dydx(l)*nor, nor, 0.d0 /)
         Xemi = (/ x(l),y(l),0.d0 /)
         call unit_vector_diff(Xemi,Xst,3,XEe)
         perp(l) = abs(DOT_PRODUCT(XEe,normal))
         write(43,*) normal(1),normal(2),normal(3),perp(l)
      end do
      close(43)
      close(44)

      ! particle accel. efficiency at the sw, depending on theta
      open(118,file=output_file('eta_acc'//number//'.dat'))
      do l = 1, ml_2
         eta_acc(l) = 2.d0*pi*( c/(vinf*perp(l)) )**2
         write(118,*) l, eta_acc(l)
      end do
      close(118)

      !-----------------------------------------------------------------
      ! Make some validity checks

      if (vinf < 1.5d8) then
         chi_rad = (vinf/1.d8)**4 * (R(1)/1.d12) / (Mdot/1.d-7/M_sun_yr) !Stevens+1992
      else
         chi_rad = 7.02 * (vinf/1.d8)**3 * (R(1)/1.d12) / (Mdot/1.d-7/M_sun_yr) !Eq. 19 from Mackey+2023
      endif
      chi_ic = 1.61 * (vinf/1.d8) * (R(1)/1.d12) / (Lst/1.d5/L_sun) * (0.62/mu_s) * (mu_es/1.18) ! Eq. 14 from Mackey+2023

      if (verbose) print *, '\n chi_rad = ',chi_rad
      if (verbose) print *, ' chi_ic = ',chi_ic 

      if (chi_rad < 1.d0) print*, '\n WARNING: chi_rad < 1, cooling is important! \n'
      if (chi_ic < 1.d0) print*, '\n WARNING: chi_ic < 1, cooling is important! \n'

      !-----------------------------------------------------------------
      !
      !  Thermodynamical quantities 
      !
      !-----------------------------------------------------------------

      cte_T = ( (g_ad-1.)/(g_ad+1.)**2 ) * (mp/k)
      cte_ad = g_ad/(g_ad-1.)
      rhow(1) = Mdot/(4.d0*pi*R(1)**2*vinf)
      P(1) = rhow(1) * vinf**2 
      rho(1) = cte_ad * 2. * P(1)/vinf**2  
      v(1) = 1.d-30 * vinf    ! Formally v(1)=0, but this can lead to divisions by zero in other modules
      Cs(1) = sqrt(g_ad*P(1)/rho(1))
      T(1) = cte_T * vinf**2
      Beq0 = sqrt(8.d0*pi*P(1))           ! P_mag_eq = B_eq**2/8*pi = P_th
      B(1) = frac_B*Beq0     ! B = frac_B * B_equipartition
      l_crit = 2             ! v(1)=0, so the first downstream cell is subsonic

      do l = 2, ml_2
         rhow(l) = Mdot/(4.d0*pi*R(l)**2*vinf)
         ! Check whether the shocked fluid is subsonic or not 
         if ( v(l-1) <= Cs(l-1) ) then        
            l_crit = l                               ! l for which shocked fluid becomes supersonic           
            P(l) = rhow(l) * vinf**2 * perp(l)
         else 
            P(l) = rhow(l) * vinf**2 * perp(l)**2/perp(l_crit)   ! sin(ang0) = v_perp(l_crit)/v_sh
         end if
         rho(l) = rho(1)*(P(l)/P(1))**(1./g_ad)
         v(l) = sqrt( 2.d0 * (0.5d0*vinf**2 - cte_ad*P(l)/rho(l)) )             
         Cs(l) = sqrt( g_ad*P(l)/rho(l) )
         T(l) = cte_T * (vinf * perp(l))**2 
         Beq0 = sqrt( 8.d0*pi*P(l) )           ! P_mag_eq = B_eq**2/8*pi = P_th
         if ( l <= l_crit ) then
            B(l) = frac_B*Beq0
         else       
            B(l) = B(l-1)*sqrt( (rho(l)*v(l-1))/(rho(l-1)*v(l)) )   ! Frozen-in conditions
         end if
      end do
      if (verbose) print*, 'l_crit =', l_crit
      ! Mirror for the lower half
      do l = ml_2+1, ml                       
         rho(l)=rho(l-ml_2)
         P(l)=P(l-ml_2)
         v(l)=v(l-ml_2)
         T(l)=T(l-ml_2)
         B(l)=B(l-ml_2)
      end do
      n_a = rho/(mp*mu_is) ! Ion/nuclei number density needed for rel. br. and p-p
      
      !------------------------------
      ! Write the results

      open(16,file=output_file('thermo'//number//'.dat'))
      open(17,file=output_file('thermo_norm'//number//'.dat'))
      do l = 1, ml
         write(16,*) l,rho(l),P(l),v(l),T(l),B(l),n_a(l)
         ! Also make a normalized one for consistency checkings 
         write(17,*) l,rho(l)/rho(1),P(l)/P(1),v(l)/vinf,T(l)/T(1),B(l)/B(1),n_a(l)/n_a(1)
      end do
      close(16)
      close(17)

      if (verbose) then 
         write(*,*) 'Apex of S'//number//':'
         write(*,41) 'rho0=',rho(1)
         write(*,41) 'P0=',P(1)
         write(*,41) 'v0=',v(1)
         write(*,41) 'T0=',T(1)
         write(*,41) 'B0=',B(1)
         write(*,41) 'Beq0=',sqrt(8.d0*pi*P(1))
         write(*,41) 'B_st'//number//'<',B(1)/4.d0*(x(1)/Rst)*(vinf/v_rot)*r_A_st
         41  format (A7,X,ES9.2)
      endif


      !------------------------------
      ! Calculate the shock's width from mass conservation

      dot_M = 0.d0
      y_min = 0.3d0 * R(1) ! For y < y_min, the approximation is not good
      l_min = int( (y_min/y(ml_2)) * ml_2 )
      do l = 1, ml_2
         dA_perp = y(l) * (Dl(l)*perp(l)) * d_phi
         dM = (rhow(l) * vinf) * dA_perp
         dot_M = dot_M + dM
         H_sh(l) = dot_M / ( d_phi*y(l)*rho(l)*v(l) )   ! dot_M = 2*pi*y_eff(l)*H_new(l)*rho(l)*v_t(l)                 
         H_sh(l+ml_2) = H_sh(l)      ! Mirror for the lower half
      end do

      ! For y < y_min, we use the value obtained at y_min
      do l = 1, l_min
         H_sh(l) = H_sh(l_min)       
         if (H_sh(l) > 0.3 * R(l)) H_sh(l) = 0.3 * R(l) ! some cells need to be arbitrarily capped         
         H_sh(l+ml_2) = H_sh(l)
      end do

      dVol(1) = 2.d0*pi*0.5d0*y(2)*H_sh(1)*Dl(1) ! Volume of the "ring"
      do l=2, ml_2
         dVol(l) = 2.d0*pi*y(l)*H_sh(l)*Dl(l) ! Volume of the "ring"
      end do

      open(15, file=output_file('H'//number//'.dat'))
      do l = 1, ml_2
         write(15,*) l, H_sh(l), H_sh(l)/R(1), H_sh(l)/R(l), dVol(l)
      end do
      close(15)

      !-----------------------------------------------------------------
      ! Injected power:
      L_wind = 0.5d0*(Mdot*vinf**2)
      
      L_inj_tot = 0.d0
      open(42,file=output_file('Linj'//number//'.dat'))
      do l = 1, ml_2
         dA_perp = y(l) * (Dl(l)*perp(l)) * d_phi
         if (l <= l_crit) then   
            e_flux = 0.5d0 * rhow(l) * vinf**3
         else 
            e_flux = 0.5d0 * rhow(l) * vinf**3 * perp(l)
         endif
         L_inj(l) = e_flux * dA_perp
         L_inj_tot = L_inj_tot + L_inj(l)

         write(42,*) x(l),y(l),L_inj(l),Dl(l)
      end do
      close(42)

      if (verbose) then 
         write(*,99) 'L_inj(S'//number//')=',L_inj_tot*(mphi*4.) ! It was just 1 quadrant
         write(*,99) 'L_NT/L_W(%)=', frac_NT*(L_inj_tot*mphi*4.)/L_wind*100.d0
      99  format (A11,X,ES12.4)
      endif

   END subroutine CD_thermo_run
   
END module CD_thermo


!============================================================================
